import test from "node:test";
import assert from "node:assert/strict";
import {createSharedMemory,createMemoryView} from "../src/core/memory.js";
import {Component,componentNamesList,EntityRegistry} from "../src/core/ecs.js";
import {EntityType,EntityTypeCode} from "../src/core/entities.js";
import {createSimulationWorld} from "../src/core/world.js";
import {SimulationCore,SIMULATION_SYSTEM_ORDER} from "../src/systems/simulation-core.js";
import {updateMovement} from "../src/systems/movement.js";
import {updateNeeds} from "../src/systems/needs.js";
import {updateConstruction} from "../src/systems/construction.js";
import {updateProduction,queueProduction} from "../src/systems/production.js";
import {MEMORY_CAPACITIES} from "../src/core/constants.js";

test("Fase 3: nove componentes arquiteturais",()=>assert.deepEqual(componentNamesList,["Position","Velocity","Job","Inventory","Needs","Building","Production","Movement","Health"]));
test("Fase 3: ECS contíguo, máscaras e consulta",()=>{const r=new EntityRegistry(8),id=r.create(EntityTypeCode[EntityType.HABITANT]);r.add(id,Component.POSITION,[1,2,3]);r.add(id,Component.HEALTH,[100,100]);assert.deepEqual([...r.get(id,Component.POSITION)],[1,2,3]);let n=0;r.query(Component.POSITION,Component.HEALTH).forEach(x=>{if(x===id)n+=1;});assert.equal(n,1);assert.throws(()=>r.query("InvalidComponent"));});
test("Fase 3: IDs são reutilizados e componentes são limpos",()=>{const r=new EntityRegistry(2),id=r.create();r.add(id,Component.HEALTH,[50,100]);assert.equal(r.destroy(id),true);assert.equal(r.create(),id);assert.equal(r.get(id,Component.HEALTH),null);});
test("Fase 3: os oito tipos de entidade existem",()=>{const r=new EntityRegistry(8);for(const type of Object.values(EntityType))r.create(EntityTypeCode[type]);assert.equal(r.size,8);});
test("Fase 3: Position/Velocity usam diretamente o SAB",()=>{const m=createMemoryView(createSharedMemory()),w=createSimulationWorld(m,MEMORY_CAPACITIES.entities),id=w.spawn(EntityType.HABITANT);w.entities.get(id,Component.POSITION)[0]=10;assert.equal(m.regions.positions[0],10);});
test("Fase 3: Movement, Needs, Construction e Production executam",()=>{const w=createSimulationWorld(),id=w.spawn(EntityType.HABITANT);w.entities.add(id,Component.MOVEMENT,[10,0,0,3]);assert.equal(updateMovement(w,1),1);assert.equal(w.entities.get(id,Component.POSITION)[0],3);const needs=w.entities.get(id,Component.NEEDS);needs.set([1,1,1,100]);updateNeeds(w);assert.deepEqual([...needs],[0,0,0,100]);const house=w.spawn(EntityType.HOUSE);const b=w.entities.get(house,Component.BUILDING);b.set([1,1,99,100]);assert.equal(updateConstruction(w),1);const saw=w.spawn(EntityType.SAWMILL);w.entities.get(saw,Component.INVENTORY)[0]=2;assert.equal(queueProduction(w,saw,"SAWMILL_PLANKS").ok,true);for(let i=0;i<30;i++)updateProduction(w);assert.equal(w.entities.get(saw,Component.INVENTORY)[1],1);});
test("Fase 3: SimulationCore executa exatamente os oito sistemas na ordem",()=>{const c=new SimulationCore(),r=c.tick();assert.equal(r.tick,1);assert.deepEqual(r.systemTrace,[...SIMULATION_SYSTEM_ORDER]);assert.equal(r.metrics.population,2);});
test("Fase 3: estado do núcleo permanece sincronizado no SAB",()=>{const m=createMemoryView(createSharedMemory()),c=new SimulationCore(m),r=c.tick();assert.equal(Atomics.load(m.regions.population,0),2);assert.ok(m.regions.positions[0]>=0);assert.deepEqual(r.systemTrace,[...SIMULATION_SYSTEM_ORDER]);});
test("Fase 3: capacidade é respeitada",()=>{assert.throws(()=>{const r=new EntityRegistry(1);r.create();r.create();},RangeError);assert.equal(new EntityRegistry(MEMORY_CAPACITIES.entities).capacity,MEMORY_CAPACITIES.entities);});
