import test from "node:test";
import assert from "node:assert/strict";
import {createLocalMemory,createMemoryView} from "../src/core/memory.js";
import {WorldMap,TerrainFlag} from "../src/world/map.js";
import {FlowField} from "../src/world/flow-field.js";
import {SpatialPartition} from "../src/world/spatial-partition.js";
import {createSimulationWorld} from "../src/core/world.js";
import {EntityType} from "../src/core/entities.js";
import {updatePathfinding} from "../src/systems/pathfinding.js";
import {SimulationCore} from "../src/systems/simulation-core.js";

test("Fase 6: grade, índice e coordenadas",()=>{const m=new WorldMap(8,6);assert.equal(m.cells,48);assert.equal(m.index(3,4),35);assert.deepEqual(m.coordinates(35),{x:3,y:4});assert.equal(m.index(-1,0),-1);});
test("Fase 6: terreno livre, obstáculo, água e custo",()=>{const m=new WorldMap(4,4);const rev=m.revision;m.setTerrain(1,1,{cost:7});assert.equal(m.getCost(1,1),7);assert.equal(m.revision,rev+1);m.setTerrain(2,2,{water:true});assert.equal(m.isBlocked(2,2),true);m.setRoad(1,1,true);assert.equal(m.flags[m.index(1,1)*4]&TerrainFlag.ROAD,TerrainFlag.ROAD);assert.equal(m.getCost(1,1),1);});
test("Fase 6: custos do terreno ficam na memória local",()=>{const mem=createMemoryView(createLocalMemory()),m=new WorldMap(8,8,mem);m.setTerrain(2,2,{cost:9});const base=m.index(2,2)*4;assert.equal(mem.regions.terrain[base+1],9);assert.equal(m.flags.buffer,mem.buffer);});
test("Fase 6: Flow Field calcula custo e direção",()=>{const m=new WorldMap(7,3);m.setTerrain(3,1,{blocked:true});const f=new FlowField(m);f.create("warehouse",[{x:6,y:1}]);const d=f.directionAt("warehouse",5,1);assert.equal(d.x,1);assert.equal(d.y,0);assert.ok(d.cost>=1);assert.equal(m.navigation[m.index(5,1)*4],1);});
test("Fase 6: Flow Field não corta cantos bloqueados",()=>{const m=new WorldMap(3,3);m.setTerrain(1,0,{blocked:true});m.setTerrain(0,1,{blocked:true});const f=new FlowField(m);f.create("target",[{x:2,y:2}]);assert.equal(f.directionAt("target",0,0).cost,-1);});
test("Fase 6: múltiplos destinos e rebuild",()=>{const m=new WorldMap(8,8),f=new FlowField(m);f.create("group",[{x:7,y:7},{x:0,y:7}]);const rev=f.get("group").revision;m.setTerrain(4,4,{blocked:true});assert.notEqual(f.rebuild("group").revision,rev);assert.equal(f.get("group").destinations.length,2);});
test("Fase 6: remove limpa a navegação",()=>{const m=new WorldMap(4,4),f=new FlowField(m);f.create("x",[{x:3,y:3}]);assert.equal(f.remove("x"),true);assert.equal(m.navigation.every(v=>v===0),true);assert.equal(m.navigationRevision,m.revision);});
test("Fase 6: Spatial Partition consulta raio",()=>{const p=new SpatialPartition(10,10,1);p.insert(1,1,1);p.insert(2,7,7);const pos=new Map([[1,[1,1]],[2,[7,7]]]),found=[];p.queryRadius(1,1,1.5,id=>pos.get(id),id=>found.push(id));assert.deepEqual(found,[1]);});
test("Fase 6: construção altera navegabilidade",()=>{const w=createSimulationWorld(null,undefined,16,16);w.bootstrap();const before=w.map.navigationRevision,id=w.spawn(EntityType.HOUSE,3,0,0);assert.ok(w.map.revision>before);w.rebuildNavigation();assert.equal(w.map.navigationRevision,w.map.revision);assert.equal(w.map.isBlocked(3,0),true);assert.ok(id>0);});
test("Fase 6: Pathfinding consulta Flow Field",()=>{const w=createSimulationWorld(null,undefined,16,16);w.bootstrap();const id=w.spawn(EntityType.HABITANT,1,1,0);w.entities.get(id,"Movement")[3]=2;assert.ok(updatePathfinding(w)>=1);const mv=w.entities.get(id,"Movement");assert.ok(mv[0]!==0||mv[1]!==0);});
test("Fase 6: mapa e navegação usam memória local",()=>{const m=createMemoryView(createLocalMemory()),w=createSimulationWorld(m);assert.equal(w.map.flags.buffer,m.buffer);assert.equal(w.map.navigation.buffer,m.buffer);});
test("Fase 6: SimulationCore mantém navegação atualizada",()=>{const m=createMemoryView(createLocalMemory()),c=new SimulationCore(m),r=c.tick();assert.equal(r.tick,1);assert.ok(c.world.navigation.activeField);assert.equal(c.world.map.navigationRevision,c.world.map.revision);});
