import test from "node:test";import assert from "node:assert/strict";
import {createSimulationWorld} from "../src/core/world.js";import {EntityType} from "../src/core/entities.js";import {RESOURCE} from "../src/systems/economy.js";import {JOB_STATE,updateLogistics} from "../src/systems/logistics.js";import {MEMORY} from "../src/core/constants.js";import {createSharedMemory,createMemoryView} from "../src/core/memory.js";import {SimulationCore} from "../src/systems/simulation-core.js";
function world(){const w=createSimulationWorld(null,undefined,32,32);w.bootstrap();return w;}
test("Fase 7: construção valida célula, estoque e consome materiais",()=>{const w=world();const warehouse=2;w.entities.get(warehouse,"Inventory")[RESOURCE.WOOD]=20;w.entities.get(warehouse,"Inventory")[RESOURCE.STONE]=10;const result=w.requestConstruction(EntityType.HOUSE,3,3);assert.equal(result.ok,true);assert.equal(w.entities.get(warehouse,"Inventory")[RESOURCE.WOOD],15);assert.equal(w.map.isBlocked(3,3),true);assert.ok(w.events.some(e=>e.type==="constructionStarted"));});
test("Fase 7: construção rejeita estoque insuficiente sem alterar o mundo",()=>{const w=world();const before=w.entities.size;const result=w.requestConstruction(EntityType.HOUSE,3,3);assert.equal(result.ok,false);assert.equal(result.reason,"insufficient-construction-stock");assert.equal(w.entities.size,before);});
test("Fase 7: produção consome entrada e gera saída",()=>{const w=world();const sawmill=3;const inv=w.entities.get(sawmill,"Inventory");inv[RESOURCE.WOOD]=4;assert.equal(w.queueProduction(sawmill,"SAWMILL_PLANKS").ok,true);const production=new SimulationCore(null,undefined,32,32);production.world.entities.get(3,"Inventory")[RESOURCE.WOOD]=4;production.tick();const out=production.world.entities.get(3,"Inventory");assert.equal(out[RESOURCE.PLANKS],1);});
test("Fase 7: logística valida e executa transporte",()=>{const w=world();const worker=5,source=2,destination=3;w.entities.get(source,"Inventory")[RESOURCE.WOOD]=6;const task=w.createLogisticsTask({workerId:worker,sourceId:source,destinationId:destination,resource:RESOURCE.WOOD,quantity:5});assert.equal(task.ok,true);updateLogistics(w);assert.equal(w.entities.get(worker,"Job")[2],JOB_STATE.READY);updateLogistics(w);assert.equal(w.entities.get(source,"Inventory")[RESOURCE.WOOD],1);assert.equal(w.entities.get(destination,"Inventory")[RESOURCE.WOOD],5);updateLogistics(w);assert.equal(w.entities.get(worker,"Job")[2],JOB_STATE.IDLE);});
test("Fase 7: logística rejeita estoque insuficiente",()=>{const w=world();const result=w.createLogisticsTask({workerId:5,sourceId:2,destinationId:3,resource:RESOURCE.WOOD,quantity:1});assert.equal(result.ok,false);assert.equal(result.reason,"insufficient-stock");});
test("Fase 7: serviços econômicos funcionam sobre SharedArrayBuffer",()=>{const memory=createMemoryView(createSharedMemory(MEMORY.INITIAL_BYTES));const core=new SimulationCore(memory);core.world.entities.get(2,"Inventory")[RESOURCE.WOOD]=20;core.world.entities.get(2,"Inventory")[RESOURCE.STONE]=10;assert.equal(core.world.requestConstruction(EntityType.HOUSE,20,20).ok,true);assert.equal(core.world.queueProduction(3,"SAWMILL_PLANKS").ok,true);core.world.entities.get(3,"Inventory")[RESOURCE.WOOD]=2;assert.equal(core.world.createLogisticsTask({workerId:5,sourceId:2,destinationId:3,resource:RESOURCE.WOOD,quantity:1}).ok,true);core.tick();assert.ok(core.world.metrics.produced>=0);});
