export function createGameUI(root,store,actions){
  if(!root)throw new Error("WebLords: raiz da interface não encontrada.");
  root.innerHTML='<div class="hud" data-ui="hud"><header class="hud__top"><div class="brand">WEBLORDS</div><div class="hud__metrics"><span data-ui="population">População: 0</span><span data-ui="tick">Tick: 0</span></div><button type="button" data-action="menu" aria-label="Abrir menu">☰</button></header><aside class="panel panel--resources" aria-label="Recursos"><h2>Recursos</h2><div data-ui="resources">Nenhum dado</div></aside><aside class="panel panel--context" data-ui="context" aria-label="Informações contextuais"><h2>Seleção</h2><div>Nenhuma entidade selecionada.</div></aside><div class="messages" data-ui="messages" aria-live="polite"></div><div class="menu" data-ui="menu-panel" hidden><button type="button" data-action="close-menu">Fechar</button><button type="button" data-action="reset">Reiniciar simulação</button></div></div>';
  const population=root.querySelector('[data-ui="population"]'),tick=root.querySelector('[data-ui="tick"]'),resources=root.querySelector('[data-ui="resources"]'),context=root.querySelector('[data-ui="context"]'),messages=root.querySelector('[data-ui="messages"]'),menu=root.querySelector('[data-ui="menu-panel"]');
  const render=()=>{population.textContent="População: "+store.state.population;tick.textContent="Tick: "+(store.state.worldState.tick??0);resources.innerHTML="";if(store.state.resources.size===0)resources.textContent="Nenhum dado";else for(const [name,value] of store.state.resources){const row=document.createElement("div");row.textContent=name+": "+value;resources.appendChild(row);}const selection=store.state.selection;context.innerHTML=selection?"<h2>Seleção</h2><div>Entidade #"+(selection.entityId??"-")+"</div><div>Tipo: "+(selection.entityType??"-")+"</div><div>Posição: "+(selection.x??"-")+", "+(selection.y??"-")+"</div>":"<h2>Seleção</h2><div>Nenhuma entidade selecionada.</div>";messages.innerHTML="";for(const message of store.state.messages.slice(-5)){const row=document.createElement("div");row.className="ui-message";row.textContent=message.type;messages.appendChild(row);}};
  const unsubscribe=store.subscribe(render);
  root.addEventListener("click",(event)=>{const action=event.target.closest("[data-action]")?.dataset.action;if(action==="menu")menu.hidden=false;if(action==="close-menu")menu.hidden=true;if(action==="reset"){menu.hidden=true;actions.reset();}});
  render();return{render,destroy(){unsubscribe();root.innerHTML="";}};
}
