import {chromium} from "playwright";
const base=process.env.BASE_URL??"http://127.0.0.1:4173";
const browser=await chromium.launch({headless:true});
const page=await browser.newPage();
const errors=[];
page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
page.on("pageerror",e=>errors.push(e.message));
const response=await page.goto(base,{waitUntil:"networkidle"});
if(!response||response.status()!==200)throw new Error("WebLords: página de produção não respondeu 200.");
const result=await page.evaluate(()=>{const canvas=document.querySelector("#game-canvas");const gl=canvas?.getContext("webgl2");const pixels=new Uint8Array(4);if(gl)gl.readPixels(Math.floor(canvas.width/2),Math.floor(canvas.height/2),1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixels);return{webgl2:!!gl,interface:!!document.querySelector("#interface"),hud:!!document.querySelector('[data-ui="hud"]'),worker:typeof Worker==="function",canvasWidth:canvas?.width??0,canvasHeight:canvas?.height??0,centerPixel:[...pixels]};});
if(!result.webgl2||!result.interface||!result.hud||!result.worker||result.canvasWidth<2||result.canvasHeight<2)throw new Error("WebLords: capacidades/UI/canvas não estão operacionais: "+JSON.stringify(result));
await page.getByRole("button",{name:"Abrir menu"}).click();
if(await page.getByRole("button",{name:"Fechar"}).count()!==1)throw new Error("WebLords: menu da UI não abriu corretamente.");
await page.getByRole("button",{name:"Fechar"}).click();
await page.waitForTimeout(150);
if(errors.length)throw new Error("WebLords: erros no navegador: "+errors.join(" | "));
await browser.close();
console.log("WebLords browser smoke: OK — Web Worker, WebGL2, HUD, menu e execução inicial validados.");
