import {chromium} from "playwright";
const base=process.env.BASE_URL??"http://127.0.0.1:4173";
const browser=await chromium.launch({headless:true});
const page=await browser.newPage();
const errors=[];
page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
page.on("pageerror",e=>errors.push(e.message));
const response=await page.goto(base,{waitUntil:"networkidle"});
if(!response||response.status()!==200)throw new Error("WebLords: página de produção não respondeu 200.");
const result=await page.evaluate(()=>({webgl2:!!document.createElement("canvas").getContext("webgl2"),interface:!!document.querySelector("#interface"),hud:!!document.querySelector('[data-ui="hud"]'),worker:typeof Worker==="function"}));
if(!result.webgl2||!result.interface||!result.hud||!result.worker)throw new Error("WebLords: capacidades/UI não estão operacionais: "+JSON.stringify(result));
await page.getByRole("button",{name:"Abrir menu"}).click();
if(await page.getByRole("button",{name:"Fechar"}).count()!==1)throw new Error("WebLords: menu da UI não abriu corretamente.");
await page.getByRole("button",{name:"Fechar"}).click();
await page.waitForTimeout(150);
if(errors.length)throw new Error("WebLords: erros no navegador: "+errors.join(" | "));
await browser.close();
console.log("WebLords browser smoke: OK — Web Worker, WebGL2, HUD, menu e execução inicial validados.");
