import {readFile,stat} from "node:fs/promises";
for(const path of ["src/core/asset-manager.js","src/core/asset-loader.js","src/core/asset-pipeline.js","src/core/asset-profiler.js","src/core/memory-budget.js","src/core/asset-manifest.js","docs/phase9-assets-memory.md","tests/phase9.test.js","assets/models/web-lords-triangle.glb"]) await stat(path);
const manager=await readFile("src/core/asset-manager.js","utf8");
for(const token of [".glb",".ktx2",".ogg","clearUnused","getStats","maxBytes"]) if(!manager.includes(token)) throw new Error("WebLords: requisito ausente: "+token);
const manifest=await readFile("src/core/asset-manifest.js","utf8");
for(const token of ["web-lords-triangle.glb","essential","optional","Meshopt","Draco"]) if(!manifest.includes(token)) throw new Error("WebLords: manifesto incompleto: "+token);
const pipeline=await readFile("src/core/asset-pipeline.js","utf8");
for(const token of ["loadAssetCatalog","loadAssetOnDemand","preloadEssentialAssets","inspectAsset"]) if(!pipeline.includes(token)) throw new Error("WebLords: pipeline incompleto: "+token);
const profiler=await readFile("src/core/asset-profiler.js","utf8");
for(const token of ["performance?.memory","EXT_disjoint_timer_query_webgl2","averageFrameMs"]) if(!profiler.includes(token)) throw new Error("WebLords: profiler incompleto: "+token);
const doc=await readFile("docs/phase9-assets-memory.md","utf8");
for(const token of ["15 MiB","64 MiB","Meshopt","Draco","sob demanda","telemetria"]) if(!doc.includes(token)) throw new Error("WebLords: requisito documental ausente: "+token);
console.log("WebLords assets check: OK — catálogo real, pipeline, memória, profiling e descarregamento validados.");
